services:
  - type: web
    name: quark-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CHROMA_DB_DIR
        value: /data/chroma
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_ID
        value: tbln3teMfz1sbqIuf
      - key: AUTH_SECRET_KEY
        generateValue: true
      - key: AUTH_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: SOFIA_API_KEY
        generateValue: true
    disk:
      name: quark-data
      mountPath: /data
      sizeGB: 10 